# Generated by Django 4.2.6 on 2023-11-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_notesection_delete_notesdata_note_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesection',
            name='section',
        ),
    ]
