# Generated by Django 4.2.6 on 2023-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_notesection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
