# Generated by Django 4.2.7 on 2023-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notesection',
            name='section_type',
            field=models.CharField(choices=[('standard', 'Standard Section'), ('completed_notes', 'Completed Tasks')], default='standard', max_length=20),
        ),
    ]
