# Generated by Django 4.2.7 on 2023-11-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_completed_note_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
